/**
 * Default Wiskr personas (design doc). Run with: npx ts-node --compiler-options '{"module":"CommonJS"}' prisma/seed-personas.ts
 * Or call from seed.ts after prisma migrate.
 */
export const DEFAULT_PERSONAS = [
  { name: "Quest", displayName: "Quest", modelString: "alibaba/qwen-qwq-32b:free", avatarUrl: "/avatars/quest.png", provider: "Alibaba", costTier: "$", description: "Exploration and research. Good at finding angles you haven't considered. Best for open ended questions and brainstorming." },
  { name: "Tina", displayName: "Tina", modelString: "meta-llama/llama-3.1-70b-instruct", avatarUrl: "/avatars/tina.png", provider: "Meta", costTier: "$", description: "Reliable generalist. Solid for everyday tasks, summaries, and drafting. The dependable workhorse." },
  { name: "Spark", displayName: "Spark", modelString: "google/gemini-2.0-flash-001", avatarUrl: "/avatars/spark.png", provider: "Google", costTier: "$", description: "Lightning fast, low cost. Best for quick questions, tangents, and side conversations where speed matters more than depth." },
  { name: "Prism", displayName: "Prism", modelString: "openai/gpt-4o-mini", avatarUrl: "/avatars/prism.png", provider: "OpenAI", costTier: "$", description: "Versatile and balanced. Good across many task types. Best when you're not sure which persona to use." },
  { name: "Sage", displayName: "Sage", modelString: "deepseek/deepseek-chat", avatarUrl: "/avatars/sage.png", provider: "DeepSeek", costTier: "$", description: "Deep knowledge and careful reasoning. Surprisingly capable for a free tier. Good for technical and analytical questions." },
  { name: "Titan", displayName: "Titan", modelString: "meta-llama/llama-3.1-405b-instruct", avatarUrl: "/avatars/titan.png", provider: "Meta", costTier: "$$", description: "Heavy lifting. Best for complex multi-step reasoning, long documents, and tasks that need sustained attention." },
  { name: "Ember", displayName: "Ember", modelString: "anthropic/claude-3-haiku", avatarUrl: "/avatars/ember.png", provider: "Anthropic", costTier: "$$", description: "Warm and conversational. Best for brainstorming, creative thinking, and conversations that need a human touch." },
  { name: "Gem", displayName: "Gem", modelString: "google/gemini-pro", avatarUrl: "/avatars/gem.png", provider: "Google", costTier: "$$", description: "Research and synthesis. Good at pulling together information from your context and making sense of it." },
  { name: "Gale", displayName: "Gale", modelString: "mistralai/mistral-large", avatarUrl: "/avatars/gale.png", provider: "Mistral", costTier: "$$", description: "Precise and efficient. Best for structured tasks, formatting, and outputs that need to be clean and exact." },
  { name: "Verse", displayName: "Verse", modelString: "anthropic/claude-3.5-sonnet", avatarUrl: "/avatars/verse.png", provider: "Anthropic", costTier: "$$$", description: "Writing and editing. Best for anything language-heavy - drafts, rewrites, tone matching, creative work." },
  { name: "Nova", displayName: "Nova", modelString: "anthropic/claude-sonnet-4", avatarUrl: "/avatars/nova.png",  provider: "Anthropic", costTier: "$$$", description: "Writing and language at frontier level. Best for demanding creative and editorial work where Verse needs a step up." },
  { name: "Aurora", displayName: "Aurora", modelString: "openai/gpt-4o", avatarUrl: "/avatars/aurora.png", provider: "OpenAI", costTier: "$$$", description: "Broad capability powerhouse. Best for complex tasks that touch multiple domains at once." },
  { name: "Dash", displayName: "Dash", modelString: "openai/gpt-4-turbo", avatarUrl: "/avatars/dash.png", provider: "OpenAI", costTier: "$$$", description: "Fast and capable. Best for Studio-quality output when you need it quickly without waiting for the heaviest models." },
  { name: "Opal", displayName: "Opal", modelString: "anthropic/claude-opus-4", avatarUrl: "/avatars/opal.png", provider: "Anthropic", costTier: "$$$", description: "Deep creative and analytical work. Best for long form thinking, complex creative projects, and tasks that need genuine wisdom." },
];
